# Generated by Django 2.2.12 on 2021-06-10 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamechallenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=20)),
                ('keterangan', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('nama_challenge', models.CharField(max_length=20)),
                ('jenis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechallenge.JenisChallenge')),
            ],
        ),
    ]
