# Generated by Django 2.2.12 on 2021-06-10 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamechallenge', '0002_challenge_jenischallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='jenis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamechallenge.JenisChallenge'),
        ),
    ]
