# Generated by Django 2.2.12 on 2021-06-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamechallenge', '0004_challenge_gamber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='gamber',
            new_name='gambar',
        ),
    ]
